services:
  - type: web
    name: barbershop-frontend
    env: static
    buildCommand: npm install && npm run build:render
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_VERSION
        value: 9
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html